# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:

  fluent-bit:
    image: xyz-filebeat:${CT_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ES_HOST=https://foo
      - HTTP_INPUT_PASSWORD=foo
      - HTTP_INPUT_USER=bar
