# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./log:/var/log/nginx
    labels:
      - nginx

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - "discovery.type=single-node"
    ports:
      - '9200:9200'
      - '9300:9300'
    labels:
      - elasticsearch

  filebeat:
    image: xyz-filebeat:latest
    #hostname: "{{.Node.Hostname}}-filebeat"
    hostname: "filebeat"
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=user
      - ELASTICSEARCH_PASSWORD=password
      - KIBANA_HOST=kibana:5601
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
    command: --strict.perms=false -e
    depends_on: ['elasticsearch', 'kibana', 'nginx']

  kibana:
    image: kibana:7.4.0
    ports:
      - '5601:5601'
    labels:
      - kibana
