filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: docker
  enabled: true
  containers.ids: '*'
- type: log
  enabled: true
  paths:
    - /var/log/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      enabled: true
      containers.ids: '*'
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch'
#  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'