# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - "discovery.type=single-node"
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://0.0.0.0:12201
        tag: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'

  logstash:
    image: xyz-logstash:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    working_dir: /usr/share/logstash/pipeline/
    environment:
      - ES_HOST=elasticsearch
      - LOGGING_INDEX=logstash-%{+YYYY.MM.dd}
    ports:
      - '8080:8080'
      - '12201:12201/udp'
    depends_on:
      - "elasticsearch"

  kibana:
    image: kibana:7.4.0
    ports:
      - '5601:5601'
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://0.0.0.0:12201
        tag: kibana
    depends_on:
      - "logstash"
