# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - "discovery.type=single-node"
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://0.0.0.0:12201
        tag: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  logstash:
    image: xyz-logstash:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    # volumes:
    #   - ./conf/:/usr/share/logstash/pipeline/
    working_dir: /usr/share/logstash/pipeline/
    environment:
      - ES_HOST=elasticsearch
      - LOGGING_INDEX=bar-logs-%{+YYYY.MM.dd}
      #- HTTP_INPUT_PASSWORD=foo
      #- HTTP_INPUT_USER=bar
    ports:
      - '8080:8080'
      - '12201:12201/udp'
#    command: bash
    networks:
      - elk
    depends_on:
      - "elasticsearch"

  kibana:
    image: kibana:7.4.0
    ports:
      - '5601:5601'
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://0.0.0.0:12201
        tag: kibana
    networks:
      - elk
    depends_on:
      - "logstash"

networks:
  elk:
    driver: bridge
